src/Entity/LigneCommande.php
<?php

namespace App\Entity;

use App\Repository\LigneCommandeRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LigneCommandeRepository::class)
 */
class LigneCommande
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $qte;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_c;

    /**
     * @ORM\ManyToOne(targetEntity=Produit::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $idp;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQte(): ?float
    {
        return $this->qte;
    }

    public function setQte(?float $qte): self
    {
        $this->qte = $qte;

        return $this;
    }

    public function getDateC(): ?\DateTimeInterface
    {
        return $this->date_c;
    }

    public function setDateC(?\DateTimeInterface $date_c): self
    {
        $this->date_c = $date_c;

        return $this;
    }

    public function getIdp(): ?Produit
    {
        return $this->idp;
    }

    public function setIdp(?Produit $idp): self
    {
        $this->idp = $idp;

        return $this;
    }
    /**
     * Transform to string
     *
     * @return string
     */
    public function __toString()
    {
    return (string) $this->getId();
    }
}

src/Form/LigneCommandeType.php
<?php

namespace App\Form;

use App\Entity\LigneCommande;
use App\Entity\Produit;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class LigneCommandeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('qte')
            ->add('date_c')
            ->add('idp',EntityType::class,['class'=>Produit::class,'choice_label'=>'designation','choice_value'=>'id']);;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => LigneCommande::class,
        ]);
    }
}

src/Controller/LigneCommandeController.php
<?php

namespace App\Controller;

use App\Entity\LigneCommande;
use App\Form\LigneCommandeType;
use App\Repository\LigneCommandeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/ligne/commande")
 */
class LigneCommandeController extends AbstractController
{
    /**
     * @Route("/", name="ligne_commande_index", methods={"GET"})
     */
    public function index(LigneCommandeRepository $ligneCommandeRepository): Response
    {
        return $this->render('ligne_commande/index.html.twig', [
            'ligne_commandes' => $ligneCommandeRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="ligne_commande_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $ligneCommande = new LigneCommande();
        $form = $this->createForm(LigneCommandeType::class, $ligneCommande);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($ligneCommande);
            $entityManager->flush();

            return $this->redirectToRoute('ligne_commande_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('ligne_commande/new.html.twig', [
            'ligne_commande' => $ligneCommande,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="ligne_commande_show", methods={"GET"})
     */
    public function show(LigneCommande $ligneCommande): Response
    {
        return $this->render('ligne_commande/show.html.twig', [
            'ligne_commande' => $ligneCommande,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="ligne_commande_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, LigneCommande $ligneCommande): Response
    {
        $form = $this->createForm(LigneCommandeType::class, $ligneCommande);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('ligne_commande_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('ligne_commande/edit.html.twig', [
            'ligne_commande' => $ligneCommande,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="ligne_commande_delete", methods={"POST"})
     */
    public function delete(Request $request, LigneCommande $ligneCommande): Response
    {
        if ($this->isCsrfTokenValid('delete'.$ligneCommande->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($ligneCommande);
            $entityManager->flush();
        }

        return $this->redirectToRoute('ligne_commande_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/ligne_commande/_delete_form.html.twig
<form method="post" action="{{ path('ligne_commande_delete', {'id': ligne_commande.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ligne_commande.id) }}">
    <button class="btn">Delete</button>
</form>

templates/ligne_commande/_form.html.twig
{{ form_start(form) }}
    
       {{ form_widget(form) }}
 
    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/ligne_commande/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit LigneCommande{% endblock %}

{% block body %}
    <h1>Edit LigneCommande</h1>

    {{ include('ligne_commande/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('ligne_commande_index') }}">back to list</a>

    {{ include('ligne_commande/_delete_form.html.twig') }}
{% endblock %}

templates/ligne_commande/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}LigneCommande index{% endblock %}

{% block body %}
    <h1>LigneCommande index</h1>

    <table class="table table-hover">
        <thead>
            <tr>
                <th>Id</th>
                <th>Qte</th>
                <th>Date_c</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for ligne_commande in ligne_commandes %}
            <tr>
                <td>{{ ligne_commande.id }}</td>
                <td>{{ ligne_commande.qte }}</td>
                <td>{{ ligne_commande.dateC ? ligne_commande.dateC|date('Y-m-d') : '' }}</td>
                <td>
                   <button type="button" class="btn btn-primary"><a href="{{ path('ligne_commande_show', {'id': ligne_commande.id}) }}">show</a></button>
                    <button type="button" class="btn btn-warning"><a href="{{ path('ligne_commande_edit', {'id': ligne_commande.id}) }}">edit</a></button>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <button type="button" class="btn btn-outline-danger"><a href="{{ path('ligne_commande_new') }}">Create new</a></button>
{% endblock %}

templates/ligne_commande/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New LigneCommande{% endblock %}

{% block body %}

    <h1>Create new LigneCommande</h1>

    {{ include('ligne_commande/_form.html.twig') }}

    <a href="{{ path('ligne_commande_index') }}">back to list</a>
{% endblock %}

templates/ligne_commande/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}LigneCommande{% endblock %}

{% block body %}
    <h1>LigneCommande</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ ligne_commande.id }}</td>
            </tr>
            <tr>
                <th>Qte</th>
                <td>{{ ligne_commande.qte }}</td>
            </tr>
            <tr>
                <th>Date_c</th>
                <td>{{ ligne_commande.dateC ? ligne_commande.dateC|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('ligne_commande_index') }}">back to list</a>

    <a href="{{ path('ligne_commande_edit', {'id': ligne_commande.id}) }}">edit</a>

    {{ include('ligne_commande/_delete_form.html.twig') }}
{% endblock %}